### ISSUE TITLE
digest-fetchのバージョンアップ対応が必要

### ISSUE THREAD

**Issue by h-takauma-i-enter** [1ft-seabass/node-red-contrib-qwatch#1]
digest-fetchノードがv1なので、v2にしてもらいたいです。

```
npm install digest-fetch@v2 node-fetch@v2
```

node-red-qwatch.jsのコードを少し書き換える必要がある模様です。

```
1: - const DigestFetch = require('digest-fetch');
1: + const DigestClient = require('digest-fetch')

33:  - const client = new DigestFetch(username , password, { algorithm: 'MD5' });
33:  + const client = new DigestClient(username , password, { algorithm: 'MD5' });
```

**Comment by 1ft-seabass** [comment]
状況把握できました～。助かります。

まさに v2 がよさそうですね。v3 だと https://www.npmjs.com/package/digest-fetch 見る限り ES5 まわりが発動しそうなので、まず v2 やってみますね。

**Comment by 1ft-seabass** [comment]
@h-takauma-i-enter 
![image](https://github.com/user-attachments/assets/00912237-417c-45ef-b61c-84e0ca7ee70a)

対応して更新してみました！

**Comment by h-takauma-i-enter** [comment]
ありがとうございます！確認できました！
